import type { JourneyEntry } from "./types";

export const journeyEntries: JourneyEntry[] = [
  {
    id: "globant1",
    position: "Fullstack Developer",
    company: "Globant Inc.",
    dateRange: "2022 — Present",
    summary: "Building high-throughput event pipelines and internal platforms.",
    stackSummary: "NodeJS, Express, Postgres, ReactJS, Tailwind, Jest",
    technologies: [
      { name: "typescript", label: "TypeScript" },
      { name: "node", label: "Node.js" },
      { name: "express", label: "Express" },
      { name: "postgresql", label: "PostgreSQL" },
      { name: "jest", label: "Jest" },
      { name: "kafka", label: "Kafka" },
      { name: "docker", label: "Docker" },
      { name: "kubernetes", label: "Kubernetes" },
      { name: "postman", label: "Postman" },
      { name: "grafana", label: "Grafana" },
      { name: "react", label: "React" },
      { name: "tailwind", label: "Tailwind" },
      { name: "githubActions", label: "GitHub Actions" },
      { name: "eslint", label: "ESLint" },
    ],
    highlights: [
      "Implemented Kafka queuing and retry strategies in the high volume leads pipeline",
      "Reduced sprint rework by enforcing CI/CD automations test with Jest via GitHub Actions",
      "Lowered time to detect and fix bugs with real-time observability (Grafana + Jira alerts).",
      "Migrated large services from JavaScript to TypeScript.",
      "Implemented Salesforce integrations from owned UIs (NodeJS, ReactJS, Salesforce)."
    ],
  },
  {
    id: "find-my-profession",
    position: "Fullstack Engineer",
    company: "Find My Profession Inc.",
    dateRange: "2021 — 2022",
    summary: "Implemented and maintained PHP/Node.js APIs, migrated legacy MySQL data with SQL scripts, built AngularJS UI/UX, maintained React interfaces, and worked directly with clients on software design.",
    stackSummary: "PHP, MySQL, NodeJS, MongoDB, AngularJS, ReactJS",
    technologies: [
      { name: "react", label: "React" },
      { name: "node", label: "Node.js" },
      { name: "php", label: "PHP" },
      { name: "mysql", label: "MySQL" },
      { name: "angular", label: "Angular" },
      { name: "mongodb", label: "MongoDB" },
      { name: "javascript", label: "JavaScript" },
    ],
    highlights: [
      "Modular dashboard builder for enterprise clients.",
      "Design system migration with tokenized theming.",
    ],
  },
  {
    id: "smarkio",
    position: "System Analyst",
    company: "Smarkio (Zenvia)",
    dateRange: "2019 — 2021",
    summary: "Accelerated chatbot delivery with a Node.js/WebSocket flow builder, improved dashboard data visualization, maintained PHP/CodeIgniter APIs, built internal Node.js libraries, and implemented Jest unit tests.",
    stackSummary: "PHP, CodeIgniter, NodeJS, Express, Jest, AWS, Docker",
    technologies: [
      { name: "php", label: "PHP" },
      { name: "codeIgniter", label: "Code Igniter" },
      { name: "node", label: "Node.js" },
      { name: "jest", label: "Jest" },
      { name: "docker", label: "Docker" },
      { name: "icloud", label: "AWS" },
      { name: "express", label: "Express" },
    ],
    highlights: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
  },
  {
    id: "embraer",
    position: "IT internt",
    company: "Embraer S.A.",
    dateRange: "2018 — 2019",
    summary: "Improved aircraft-part 3D model creation and issue detection through CATIA automation, developed VB.NET Excel I/O tools, and built a PHP server with SAP EWM integration to store and manipulate 3D data.",
    stackSummary: "PHP, Javascript, C#, MySQL",
    technologies: [
      { name: "php", label: "PHP" },
      { name: "javascript", label: "JavaScript" },
      { name: "csharp", label: "C#" },
      { name: "mysql", label: "MySQL" },
    ],
    highlights: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
  },
  {
    id: "black-bee-drones",
    position: "Volunteer Developer",
    company: "Black Bee Drones",
    dateRange: "2017 — 2018",
    summary: "Developed and maintained C++ and Python code, built OpenCV-based computer vision features for drone competitions, and researched TensorFlow approaches for computer vision algorithms.",
    stackSummary: "C++, Python, Tensorflow, Opencv",
    technologies: [
      { name: "cplusplus", label: "C++" },
      { name: "python", label: "Python" },
      { name: "tensorflow", label: "Tensorflow" },
      { name: "opencv", label: "Opencv" },
    ],
    highlights: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
  },
];
