import type { JourneyEntry } from "./types";

export const journeyEntries: JourneyEntry[] = [
  {
    id: "globant1",
    position: "Fullstack Developer",
    company: "Globant Inc.",
    dateRange: "2022 — Present",
    summary: "Building high-throughput event pipelines and internal platforms.",
    stackSummary: "TypeScript, Node, Express, Postgres, React, Tailwind",
    technologies: [
      { name: "typescript", label: "TypeScript" },
      { name: "node", label: "Node.js" },
      { name: "express", label: "Express" },
      { name: "postgresql", label: "PostgreSQL" },
      { name: "jest", label: "Jest" },
      { name: "kafka", label: "Kafka" },
      { name: "docker", label: "Docker" },
      { name: "kubernetes", label: "Kubernetes" },
      { name: "postman", label: "Postman" },
      { name: "grafana", label: "Grafana" },
      { name: "react", label: "React" },
      { name: "tailwind", label: "Tailwind" },
      { name: "githubActions", label: "GitHub Actions" },
    ],
    projects: [
      "Event ingestion service for real-time analytics.",
      "Internal tooling for release orchestration and metrics.",
    ],
    achievements: [
      "Reduced processing latency by ~40% through batching improvements.",
      "Improved reliability with automated backfill and retry logic.",
    ],
  },
  {
    id: "find-my-profession",
    position: "Fullstack Engineer",
    company: "Find My Profession",
    dateRange: "2021 — 2022",
    summary: "Shipped customer dashboards and design systems for B2B SaaS.",
    stackSummary: "PHP, MySQL, Node, MongoDB, AngularJS, ReactJs",
    technologies: [
      { name: "react", label: "React" },
      { name: "node", label: "Node.js" },
      { name: "php", label: "PHP" },
      { name: "mysql", label: "MySQL" },
      { name: "angular", label: "Angular" },
      { name: "mongodb", label: "MongoDB" },
      { name: "javascript", label: "JavaScript" },
    ],
    projects: [
      "Modular dashboard builder for enterprise clients.",
      "Design system migration with tokenized theming.",
    ],
    achievements: [
      "Cut feature delivery time by ~30% with shared UI primitives.",
      "Increased weekly active usage by ~20% after UX refresh.",
    ],
  },
  {
    id: "smarkio",
    position: "System Analyst",
    company: "Smarkio (Zenvia)",
    dateRange: "2019 — 2021",
    summary: "Built APIs and tooling that improved developer velocity.",
    stackSummary: "PHP, CodeIgniter, Node, Express, Jest, AWS, Docker",
    technologies: [
      { name: "php", label: "PHP" },
      { name: "codeIgniter", label: "Code Igniter" },
      { name: "node", label: "Node.js" },
      { name: "jest", label: "Jest" },
      { name: "docker", label: "Docker" },
      { name: "icloud", label: "AWS" },
      { name: "express", label: "Express" },
    ],
    projects: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
    achievements: [
      "Reduced onboarding time from days to hours with automation.",
      "Stabilized deployments by improving rollback tooling.",
    ],
  },
  {
    id: "embraer",
    position: "IT internt",
    company: "Embraer S.A.",
    dateRange: "2018 — 2019",
    summary: "Built APIs and tooling that improved developer velocity.",
    stackSummary: "PHP, Javascript, C#, MySQL",
    technologies: [
      { name: "php", label: "PHP" },
      { name: "javascript", label: "JavaScript" },
      { name: "csharp", label: "C#" },
      { name: "mysql", label: "MySQL" },
    ],
    projects: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
    achievements: [
      "Reduced onboarding time from days to hours with automation.",
      "Stabilized deployments by improving rollback tooling.",
    ],
  },
  {
    id: "black-bee-drones",
    position: "Volunteer Developer",
    company: "Black Bee Drones",
    dateRange: "2017 — 2018",
    summary: "Built APIs and tooling that improved developer velocity.",
    stackSummary: "C++, Python, Tensorflow, Opencv",
    technologies: [
      { name: "cplusplus", label: "C++" },
      { name: "python", label: "Python" },
      { name: "tensorflow", label: "Tensorflow" },
      { name: "opencv", label: "Opencv" },
    ],
    projects: [
      "Internal API gateway with auditing and rate limiting.",
      "Developer CLI for environment provisioning.",
    ],
    achievements: [
      "Reduced onboarding time from days to hours with automation.",
      "Stabilized deployments by improving rollback tooling.",
    ],
  },
];
