import type { SimpleIcon } from "simple-icons";
import {
  siApachekafka,
  siDocker,
  siExpress,
  siGraphql,
  siGrafana,
  siGithubactions,
  siJest,
  siKubernetes,
  siNextdotjs,
  siNodedotjs,
  siPostgresql,
  siPostman,
  siReact,
  siRedis,
  siTailwindcss,
  siTypescript,
  siVercel,
  siPhp,
  siSymphony,
  siAngular,
  siMongodb,
  siMysql,
  siJavascript,
  siCodeigniter,
  siIcloud,
  siOpenapiinitiative,
  siOpencv,
  siPython,
  siTensorflow,
  siCplusplus,
  siDotnet,
  siSap,
  siSharp
} from "simple-icons";

export const TECH_ICON_MAP = {
  typescript: siTypescript,
  node: siNodedotjs,
  kafka: siApachekafka,
  postgresql: siPostgresql,
  redis: siRedis,
  docker: siDocker,
  react: siReact,
  nextjs: siNextdotjs,
  tailwind: siTailwindcss,
  graphql: siGraphql,
  vercel: siVercel,
  express: siExpress,
  jest: siJest,
  kubernetes: siKubernetes,
  postman: siPostman,
  grafana: siGrafana,
  githubActions: siGithubactions,
  php: siPhp,
  symphony: siSymphony,
  angular: siAngular,
  mongodb: siMongodb,
  mysql: siMysql,
  javascript: siJavascript,
  codeIgniter: siCodeigniter,
  openapi: siOpenapiinitiative,
  icloud: siIcloud,
  opencv: siOpencv,
  python: siPython,
  tensorflow: siTensorflow,
  cplusplus: siCplusplus,
  dotnet: siDotnet,
  sap: siSap,
  csharp: siSharp,
} satisfies Record<string, SimpleIcon>;

export type TechIconName = keyof typeof TECH_ICON_MAP;
